" Ref to: http://amix.dk/vim/vimrc.html

"""""""""""" Vundle """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" PACKAGE MANAGEMENT FOR PYTHON
" Turn on Improvements feature of VI
" It's better to set vundle ahead of other things
" To startup you need install vundle at first:
" $ git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" Then make sure vundle setting is correct and intended.
" Finally install plugins: lanch vim and run ":PluginInstall"

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Bundle from github
" No [.vim] suffix is needed
" Flake8-vim: frosted, pep8 and mcabe checker for Vim
Plugin 'andviro/flake8-vim'

" https://github.com/davidhalter/jedi-vim
" jedi-vim is a VIM binding to the autocompletion library Jedi
" you need to install jedi at first `pip install jedi`
" Bundle 'davidhalter/jedi-vim'

Plugin 'ervandew/supertab'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line



"""""""""""" General """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Sets how many lines of history VIM has to remember
set history=700

" Enable filetype plugins (conflict with vundle)
" filetype on

" Set to auto read when a file is changed from the outside
set autoread

"""""""""""" Vim User Interface """"""""""""""""""""""""""""""""""""""""""""""""
" About wildmenu:
" http://vim.wikia.com/wiki/Great_wildmode/wildmenu_and_console_mouse
" Turn on the WiLd menu
set wildmenu
"set wildmode=list:longest,full " Not enjoyable with mintty

" Ignore compiled files
set wildignore=*.o,*~,*.pyc

" Display line number
set number
" 为方便复制，用<F2>开启/关闭行号显示
"nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>

" Always show current position
set ruler

" 在状态栏显示正在输入的命令
set showcmd

"Height of the command bar
set cmdheight=2

" A buffer becomes hidden when it is abandoned
set hid

" Configure backspace so it acts as it should act
"set backspace=eol,start,indent
set backspace=indent,eol,start " For cygwin
set whichwrap+=<,>,h,l

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases 
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Don't auto indent when paste text
" http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
" http://stackoverflow.com/questions/2514445/turning-off-auto-indent-when-pasting-text-into-vim
set paste

"""""""""""" color scheme """"""""""""""""""""""""""""""""""""""""""""""""""""""
"let g:molokai_original=1
colorscheme desert
set background=dark

" Enable syntax highlighting
syntax on

"""""""""""" Chinese encoding """"""""""""""""""""""""""""""""""""""""""""""""""
" http://blog.segmentfault.com/tcstory/1190000000450806
" Set utf8 as standard encoding and en_US as the standard language ?
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1


" Use Unix as the standard file type
set ffs=unix,dos,mac

"""""""""""" Files, backups and undo """""""""""""""""""""""""""""""""""""""""""
" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile

"""""""""""" Text, tab and indent related """""""""""""""""""""""""""""""""""""""
" Use spaces instead of tabs
set expandtab

" Be smart when using tabs ;) what does this mean?
set smarttab

" Auto indent, align the new line indent with the previous line
set autoindent

" Indent width, operation >> indents 4 columns; << unindents 4 columns
set shiftwidth=4

" <TAB> width, a hard TAB displays as 4 columns
set tabstop=4

" Linebreak on 500 characters, break the line manually
set lbr
set tw=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" Line Length Marker
" https://superuser.com/questions/249779/how-to-setup-a-line-length-marker-in-vim-gvim
highlight ColorColumn guibg=#2d2d2d ctermbg=20
call matchadd('ColorColumn', '\%81v', 100)

"""""""""""" Flake8-vim """"""""""""""""""""""""""""""""""""""""""""""""""""""""
" https://github.com/andviro/flake8-vim
" Auto-check file for errors on write
let g:PyFlakeOnWrite = 0
" List of checkers used
let g:PyFlakeCheckers = 'pep8,mccabe,frosted'

"""""""""""" Jedi-vim """"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" https://github.com/davidhalter/jedi-vim
" Install jedi at first: pip install jedi
let g:jedi#completions_command = "<C-e>"

"""""""""""" Supertab """"""""""""""""""""""""""""""""""""""""""""""""""""""""""

